name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Setup-the-environement:
    runs-on: windows-latest
    steps:
      - name: Action Checkout
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: RENV Install
        uses: r-lib/actions/setup-renv@v2
        